#!/bin/bash

#$1 is the command to be run.
#$2 is the title.

if [ -f /usr/bin/x-terminal-emulator ];then
  $(readlink -f /usr/bin/x-terminal-emulator) -e bash -c "$1"
else
  echo "Failed to locate any terminal emulators!!!"
  exit 1
fi
