#!/usr/bin/bash
while true;do
	mkdir -p ~/.local/share/ATlauncher/webpage
	cd ~/.local/share/ATlauncher/webpage
	wget -q https://github.com/ATLauncher/ATLauncher/releases/latest
	mkdir -p ~/.local/share/ATlauncher/webpage/old/
	[ ! "$(cat latest)" == "$(cat old/latest)" ]
	if [ $? == 1 ];then
		wget -q --show-progress https://atlauncher.com/download/jar --output-document launcher.jar || error failed to download "launcher.jar"
		mkdir -p launcher && cd launcher && mkdir -p ./assets/image && wget -q https://raw.githubusercontent.com/pi-dev500/MinecraftMicrosoftPILauncher/main/SplashScreen.png && mv SplashScreen.png assets/image/splash-screen.png && zip -rm ../launcher.jar * >/dev/null && cd .. && rm -rf launcher
	fi
	sleep 1h
	mv latest old/latest
done
