#!/bin/bash

DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

#use the error function often!
#If a certain command is necessary for installation to continue, then add this to the end of it:
# || error 'reason'
#example below:

#Download java and launcher
#Download java and launcher
mkdir -p ~/ATlauncher && cd ~/ATlauncher && wget -q https://raw.githubusercontent.com/pi-dev500/MinecraftMicrosoftPILauncher/main/setupMC.sh && chmod +x setupMC.sh && ./setupMC.sh || error "failled to download Minecraft"

#Move launcher to /usr/share/
mkdir -p $HOME/.local/share/ATlauncher && mkdir -p /usr/share/Atlauncher/jarfile && sudo ln -s -f $HOME/.local/share/ATlauncher /usr/share/ && sudo mv launcher.jar /usr/share/Atlauncher/jarfile/launcher.jar

#Create desktop shortcut
cp ${DIR}/icon-64.png /usr/share/ATlauncher/icon-64.png
cd ~/.local/share/applications/
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=ATlauncher
Comment=3D block based sandbox game
Icon=/usr/share/Atlauncher/icon-64.png
Exec=java -jar $HOME/.local/share/ATlauncher/jarfile/launcher.jar
Categories=Game;
" >ATlauncher.desktop
chmod +x ATlauncher.desktop
cd
mkdir -p $HOME/.local/share/ATlauncher/jarfile/configs
echo '{
  "usingCustomJavaPath": false,
  "hideOldJavaWarning": false,
  "firstTimeRun": false,
  "hideJava9Warning": true,
  "addedPacks": [],
  "ignoreOneDriveWarning": false,
  "ignoreProgramFilesWarning": false,
  "rememberWindowSizePosition": false,
  "consoleSize": {
    "width": 650,
    "height": 400
  },
  "consolePosition": {
    "x": 0,
    "y": 0
  },
  "launcherSize": {
    "width": 1200,
    "height": 700
  },
  "language": "anglais",
  "theme": "com.atlauncher.themes.Vuesion",
  "dateFormat": "dd/MM/yyyy",
  "selectedTabOnStartup": 0,
  "sortPacksAlphabetically": false,
  "showPackNameAndVersion": true,
  "keepLauncherOpen": true,
  "enableConsole": true,
  "enableTrayMenu": true,
  "enableDiscordIntegration": true,
  "enableFeralGamemode": true,
  "disableAddModRestrictions": false,
  "disableCustomFonts": false,
  "useNativeFilePicker": false,
  "initialMemory": 512,
  "maximumMemory": 512,
  "metaspace": 256,
  "windowWidth": 854,
  "windowHeight": 480,
  "javaPath": "/opt/jdk/jdk1.8.0_251/bin/java",
  "javaParameters": "-Dorg.lwjgl.librarypath='$HOME'/lwjgl3arm32 -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M",
  "maximiseMinecraft": false,
  "ignoreJavaOnInstanceLaunch": false,
  "concurrentConnections": 8,
  "connectionTimeout": 30,
  "enableProxy": false,
  "proxyHost": "",
  "proxyPort": 8080,
  "proxyType": "HTTP",
  "forgeLoggingLevel": "INFO",
  "enableLogs": true,
  "enableAnalytics": true,
  "analyticsClientId": "30662333-d88f-4e21-8d77-95739af9bf78",
  "enableOpenEyeReporting": true,
  "enableServerChecker": false,
  "serverCheckerWait": 5,
  "enableModsBackups": false,
  "enableAutomaticBackupAfterLaunch": false
}' > $HOME/.local/share/ATlauncher/jarfile/configs/ATLauncher.json

sudo rm -rf ~/ATlauncher

echo 'Installation is now done! You can open the launcher by going to Menu > Games > Minecraft Launcher'
echo -e "\e[21m\e[5mWARNING:\e[0m\e[97mYou can only play Minecraft versions \e[1m1.13\e[0m and higher with your current configuration! To use lower versions, please follow the instructions at \e[96mhttps://www.noxxtech.tk/minecraft-install#h.fpnon3xvmuoz\e[39m to play versions \e[1m1.12\e[0m and under!"
read -p "Press [Enter] to continue after you've read the above message"

