#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}
rm -f ~/.config/autostart/ATlauncher.desktop
rm -f ~/.local/share/applications/ATlauncher.desktop
rm -rf ~/lwjgl2arm32
rm -rf ~/lwjgl3arm32
rm -rf ~/lwjgl3arm64
rm -rf ~/.local/share/ATlauncher
